export const OFFICIAL_PLAYERS_DB = [
  // --- PORTIERI (60) ---
  { name: 'Bijlow', team: 'Genoa', role: 'P' },
  { name: 'Butez', team: 'Como', role: 'P' },
  { name: 'Caprile', team: 'Cagliari', role: 'P' },
  { name: 'Carnesecchi', team: 'Atalanta', role: 'P' },
  { name: 'Christensen O.', team: 'Fiorentina', role: 'P' },
  { name: 'Contini', team: 'Napoli', role: 'P' },
  { name: 'Corvi', team: 'Parma', role: 'P' },
  { name: 'Daffara', team: 'Parma', role: 'P' },
  { name: 'De Gea', team: 'Fiorentina', role: 'P' },
  { name: 'De Marzi', team: 'Roma', role: 'P' },
  { name: 'Desplanches', team: 'Frosinone', role: 'P' },
  { name: 'Di Gennaro', team: 'Inter', role: 'P' },
  { name: 'Di Gregorio', team: 'Juventus', role: 'P' },
  { name: 'Falcone', team: 'Lecce', role: 'P' },
  { name: 'Gollini', team: 'Roma', role: 'P' },
  { name: 'Grandi', team: 'Venezia', role: 'P' },
  { name: 'Happonen', team: 'Bologna', role: 'P' },
  { name: 'Lezzerini', team: 'Fiorentina', role: 'P' },
  { name: 'Lolic', team: 'Frosinone', role: 'P' },
  { name: 'Maignan', team: 'Milan', role: 'P' },
  { name: 'Mandas', team: 'Lazio', role: 'P' },
  { name: 'Martinez Jo.', team: 'Inter', role: 'P' },
  { name: 'Mascardi', team: 'Torino', role: 'P' },
  { name: 'Meret', team: 'Napoli', role: 'P' },
  { name: 'Milinkovic-Savic V.', team: 'Napoli', role: 'P' },
  { name: 'Motta', team: 'Lazio', role: 'P' },
  { name: 'Muric', team: 'Sassuolo', role: 'P' },
  { name: 'Okoye', team: 'Udinese', role: 'P' },
  { name: 'Padelli', team: 'Udinese', role: 'P' },
  { name: 'Paleari', team: 'Torino', role: 'P' },
  { name: 'Palmisani', team: 'Frosinone', role: 'P' },
  { name: 'Penev', team: 'Lecce', role: 'P' },
  { name: 'Perin', team: 'Juventus', role: 'P' },
  { name: 'Pessina Mas.', team: 'Bologna', role: 'P' },
  { name: 'Piana', team: 'Udinese', role: 'P' },
  { name: 'Pinsoglio', team: 'Juventus', role: 'P' },
  { name: 'Pizzignacco', team: 'Monza', role: 'P' },
  { name: 'Pozzi', team: 'Venezia', role: 'P' },
  { name: 'Provedel', team: 'Inter', role: 'P' },
  { name: 'Radunovic', team: 'Cagliari', role: 'P' },
  { name: 'Renzetti', team: 'Lazio', role: 'P' },
  { name: 'Russo A.', team: 'Sassuolo', role: 'P' },
  { name: 'Sherri', team: 'Cagliari', role: 'P' },
  { name: 'Siviero', team: 'Torino', role: 'P' },
  { name: 'Skorupski', team: 'Bologna', role: 'P' },
  { name: 'Sommariva', team: 'Genoa', role: 'P' },
  { name: 'Sportiello', team: 'Atalanta', role: 'P' },
  { name: 'Stankovic F.', team: 'Venezia', role: 'P' },
  { name: 'Stolz', team: 'Genoa', role: 'P' },
  { name: 'Strajnar', team: 'Monza', role: 'P' },
  { name: 'Suzuki', team: 'Parma', role: 'P' },
  { name: 'Svilar', team: 'Roma', role: 'P' },
  { name: 'Terracciano', team: 'Milan', role: 'P' },
  { name: 'Thiam', team: 'Monza', role: 'P' },
  { name: 'Tornqvist', team: 'Como', role: 'P' },
  { name: 'Torriani', team: 'Milan', role: 'P' },
  { name: 'Turati', team: 'Sassuolo', role: 'P' },
  { name: 'Vicario', team: 'Juventus', role: 'P' },
  { name: 'Vigorito', team: 'Como', role: 'P' },
  { name: 'Vismara', team: 'Atalanta', role: 'P' },

  // --- DIFENSORI (177) ---
  { name: 'Abankwah', team: 'Udinese', role: 'D' },
  { name: 'Ahanor', team: 'Atalanta', role: 'D' },
  { name: 'Akanji', team: 'Inter', role: 'D' },
  { name: 'Akpoguma', team: 'Frosinone', role: 'D' },
  { name: 'Alhassane', team: 'Bologna', role: 'D' },
  { name: 'Amey', team: 'Frosinone', role: 'D' },
  { name: 'Antov', team: 'Monza', role: 'D' },
  { name: 'Arizala', team: 'Udinese', role: 'D' },
  { name: 'Aurelio', team: 'Cagliari', role: 'D' },
  { name: 'Bakoune', team: 'Monza', role: 'D' },
  { name: 'Bartesaghi', team: 'Milan', role: 'D' },
  { name: 'Bastoni', team: 'Inter', role: 'D' },
  { name: 'Bella-Kotchap', team: 'Venezia', role: 'D' },
  { name: 'Bellanova', team: 'Atalanta', role: 'D' },
  { name: 'Bernasconi', team: 'Atalanta', role: 'D' },
  { name: 'Bertola', team: 'Udinese', role: 'D' },
  { name: 'Beukema', team: 'Napoli', role: 'D' },
  { name: 'Biraghi', team: 'Torino', role: 'D' },
  { name: 'Birindelli', team: 'Monza', role: 'D' },
  { name: 'Bisseck', team: 'Inter', role: 'D' },
  { name: 'Bracaglia', team: 'Frosinone', role: 'D' },
  { name: 'Bremer', team: 'Juventus', role: 'D' },
  { name: 'Britschgi', team: 'Parma', role: 'D' },
  { name: 'Buongiorno', team: 'Napoli', role: 'D' },
  { name: 'Cabal', team: 'Juventus', role: 'D' },
  { name: 'Calvani', team: 'Frosinone', role: 'D' },
  { name: 'Cambiaso', team: 'Juventus', role: 'D' },
  { name: 'Candè', team: 'Sassuolo', role: 'D' },
  { name: 'Carboni A.', team: 'Monza', role: 'D' },
  { name: 'Carboni F.', team: 'Parma', role: 'D' },
  { name: 'Carlos Augusto', team: 'Inter', role: 'D' },
  { name: 'Casale', team: 'Bologna', role: 'D' },
  { name: 'Celik', team: 'Juventus', role: 'D' },
  { name: 'Chalobah T.', team: 'Como', role: 'D' },
  { name: 'Circati', team: 'Parma', role: 'D' },
  { name: 'Cittadini', team: 'Frosinone', role: 'D' },
  { name: 'Coco', team: 'Torino', role: 'D' },
  { name: 'Comert', team: 'Torino', role: 'D' },
  { name: 'Comuzzo', team: 'Torino', role: 'D' },
  { name: 'Corrado', team: 'Frosinone', role: 'D' },
  { name: 'Correia T.', team: 'Venezia', role: 'D' },
  { name: 'Couto', team: 'Como', role: 'D' },
  { name: 'Cuenca A.', team: 'Como', role: 'D' },
  { name: 'De Silvestri', team: 'Bologna', role: 'D' },
  { name: 'De Winter', team: 'Milan', role: 'D' },
  { name: 'Delli Carri', team: 'Monza', role: 'D' },
  { name: 'Delprato', team: 'Parma', role: 'D' },
  { name: 'Di Lorenzo', team: 'Napoli', role: 'D' },
  { name: 'Diawara S.', team: 'Milan', role: 'D' },
  { name: 'Dimarco', team: 'Inter', role: 'D' },
  { name: 'Dodo', team: 'Fiorentina', role: 'D' },
  { name: 'Doekhi', team: 'Lazio', role: 'D' },
  { name: 'Doig', team: 'Sassuolo', role: 'D' },
  { name: 'Dragusin', team: 'Fiorentina', role: 'D' },
  { name: 'Ebosse', team: 'Udinese', role: 'D' },
  { name: 'Estupinan', team: 'Milan', role: 'D' },
  { name: 'Floriani Mussolini', team: 'Lazio', role: 'D' },
  { name: 'Franjic', team: 'Venezia', role: 'D' },
  { name: 'Gabbia', team: 'Milan', role: 'D' },
  { name: 'Gallo', team: 'Lecce', role: 'D' },
  { name: 'Gaspar K.', team: 'Lecce', role: 'D' },
  { name: 'Gatti', team: 'Juventus', role: 'D' },
  { name: 'Gelli J.', team: 'Frosinone', role: 'D' },
  { name: 'Ghilardi', team: 'Roma', role: 'D' },
  { name: 'Gila', team: 'Milan', role: 'D' },
  { name: 'Goldaniga', team: 'Como', role: 'D' },
  { name: 'Gomes', team: 'Venezia', role: 'D' },
  { name: 'Hainaut', team: 'Venezia', role: 'D' },
  { name: 'Halhal', team: 'Venezia', role: 'D' },
  { name: 'Haps', team: 'Venezia', role: 'D' },
  { name: 'Heggem', team: 'Bologna', role: 'D' },
  { name: 'Helland', team: 'Bologna', role: 'D' },
  { name: 'Hermoso', team: 'Roma', role: 'D' },
  { name: 'Hien', team: 'Atalanta', role: 'D' },
  { name: 'Holm', team: 'Bologna', role: 'D' },
  { name: 'Idrissi R.', team: 'Cagliari', role: 'D' },
  { name: 'Idzes', team: 'Sassuolo', role: 'D' },
  { name: 'Ismajli', team: 'Torino', role: 'D' },
  { name: 'Jean', team: 'Lecce', role: 'D' },
  { name: 'Jimenez A.', team: 'Fiorentina', role: 'D' },
  { name: 'Joao Mario', team: 'Fiorentina', role: 'D' },
  { name: 'Kabasele', team: 'Udinese', role: 'D' },
  { name: 'Kaiki', team: 'Como', role: 'D' },
  { name: 'Kalulu', team: 'Juventus', role: 'D' },
  { name: 'Kamara H.', team: 'Udinese', role: 'D' },
  { name: 'Kelly L.', team: 'Juventus', role: 'D' },
  { name: 'Kempf', team: 'Como', role: 'D' },
  { name: 'Kofler', team: 'Cagliari', role: 'D' },
  { name: 'Kolasinac', team: 'Atalanta', role: 'D' },
  { name: 'Kossounou', team: 'Atalanta', role: 'D' },
  { name: 'Kouadio', team: 'Monza', role: 'D' },
  { name: 'Koulierakis', team: 'Roma', role: 'D' },
  { name: 'Kristensen T.', team: 'Atalanta', role: 'D' },
  { name: 'Lazzari', team: 'Lazio', role: 'D' },
  { name: 'Lucchesi', team: 'Monza', role: 'D' },
  { name: 'Lucumi', team: 'Juventus', role: 'D' },
  { name: 'Mancini', team: 'Roma', role: 'D' },
  { name: 'Mangas', team: 'Monza', role: 'D' },
  { name: 'Marcandalli', team: 'Genoa', role: 'D' },
  { name: 'Marianucci', team: 'Napoli', role: 'D' },
  { name: 'Marin R.', team: 'Napoli', role: 'D' },
  { name: 'Martin', team: 'Genoa', role: 'D' },
  { name: 'Marusic', team: 'Lazio', role: 'D' },
  { name: 'Matturro', team: 'Genoa', role: 'D' },
  { name: 'Mazzocchi', team: 'Napoli', role: 'D' },
  { name: 'Mina', team: 'Cagliari', role: 'D' },
  { name: 'Miranda J.', team: 'Bologna', role: 'D' },
  { name: 'Missori', team: 'Sassuolo', role: 'D' },
  { name: 'Mitaj', team: 'Genoa', role: 'D' },
  { name: 'Mlacic', team: 'Udinese', role: 'D' },
  { name: 'Molina N.', team: 'Roma', role: 'D' },
  { name: 'Monterisi', team: 'Frosinone', role: 'D' },
  { name: 'Moreno M.', team: 'Venezia', role: 'D' },
  { name: 'N\'Dicka', team: 'Roma', role: 'D' },
  { name: 'Ndaba', team: 'Lecce', role: 'D' },
  { name: 'Ndiaye', team: 'Parma', role: 'D' },
  { name: 'Norton-Cuffy', team: 'Genoa', role: 'D' },
  { name: 'Obert', team: 'Cagliari', role: 'D' },
  { name: 'Obrador', team: 'Sassuolo', role: 'D' },
  { name: 'Olivera', team: 'Napoli', role: 'D' },
  { name: 'Ostigard', team: 'Genoa', role: 'D' },
  { name: 'Otoa', team: 'Genoa', role: 'D' },
  { name: 'Oyono A.', team: 'Frosinone', role: 'D' },
  { name: 'Oyono J.', team: 'Frosinone', role: 'D' },
  { name: 'Palma', team: 'Udinese', role: 'D' },
  { name: 'Parisi', team: 'Fiorentina', role: 'D' },
  { name: 'Patric', team: 'Lazio', role: 'D' },
  { name: 'Pavard', team: 'Inter', role: 'D' },
  { name: 'Pavlovic', team: 'Milan', role: 'D' },
  { name: 'Pedersen', team: 'Torino', role: 'D' },
  { name: 'Pedraza', team: 'Lazio', role: 'D' },
  { name: 'Pellegrini Lu.', team: 'Lazio', role: 'D' },
  { name: 'Pieragnolo', team: 'Sassuolo', role: 'D' },
  { name: 'Pongracic', team: 'Fiorentina', role: 'D' },
  { name: 'Provstgaard', team: 'Lazio', role: 'D' },
  { name: 'Puczka', team: 'Genoa', role: 'D' },
  { name: 'Ramon', team: 'Como', role: 'D' },
  { name: 'Ranieri L.', team: 'Fiorentina', role: 'D' },
  { name: 'Rensch', team: 'Roma', role: 'D' },
  { name: 'Rodriguez Ju.', team: 'Cagliari', role: 'D' },
  { name: 'Romagnoli', team: 'Lazio', role: 'D' },
  { name: 'Rrahmani', team: 'Napoli', role: 'D' },
  { name: 'Rugani', team: 'Juventus', role: 'D' },
  { name: 'Sabelli', team: 'Genoa', role: 'D' },
  { name: 'Sagrado', team: 'Venezia', role: 'D' },
  { name: 'Scalvini', team: 'Atalanta', role: 'D' },
  { name: 'Schingtienne', team: 'Venezia', role: 'D' },
  { name: 'Siebert', team: 'Lecce', role: 'D' },
  { name: 'Smolcic I.', team: 'Como', role: 'D' },
  { name: 'Solet', team: 'Udinese', role: 'D' },
  { name: 'Spence', team: 'Inter', role: 'D' },
  { name: 'Spinazzola', team: 'Napoli', role: 'D' },
  { name: 'Stones', team: 'Inter', role: 'D' },
  { name: 'Sverko', team: 'Venezia', role: 'D' },
  { name: 'Tavares N.', team: 'Lazio', role: 'D' },
  { name: 'Terzic', team: 'Frosinone', role: 'D' },
  { name: 'Tiago Gabriel', team: 'Lecce', role: 'D' },
  { name: 'Tomori', team: 'Milan', role: 'D' },
  { name: 'Troilo', team: 'Parma', role: 'D' },
  { name: 'Valdepenas', team: 'Fiorentina', role: 'D' },
  { name: 'Valenti', team: 'Parma', role: 'D' },
  { name: 'Valeri', team: 'Parma', role: 'D' },
  { name: 'Valle', team: 'Como', role: 'D' },
  { name: 'Van Der Brempt', team: 'Como', role: 'D' },
  { name: 'Vasquez', team: 'Genoa', role: 'D' },
  { name: 'Veiga D.', team: 'Lecce', role: 'D' },
  { name: 'Viery', team: 'Fiorentina', role: 'D' },
  { name: 'Vitik', team: 'Bologna', role: 'D' },
  { name: 'Vojvoda', team: 'Udinese', role: 'D' },
  { name: 'Walukiewicz', team: 'Sassuolo', role: 'D' },
  { name: 'Wesley', team: 'Roma', role: 'D' },
  { name: 'Zanoli', team: 'Udinese', role: 'D' },
  { name: 'Zappa', team: 'Cagliari', role: 'D' },
  { name: 'Zappacosta', team: 'Atalanta', role: 'D' },
  { name: 'Zè Pedro', team: 'Cagliari', role: 'D' },
  { name: 'Ziolkowski', team: 'Roma', role: 'D' },
  { name: 'Zortea', team: 'Bologna', role: 'D' },

  // --- CENTROCAMPISTI (177) ---
  { name: 'Aboukhlal', team: 'Torino', role: 'C' },
  { name: 'Addai', team: 'Como', role: 'C' },
  { name: 'Adopo', team: 'Cagliari', role: 'C' },
  { name: 'Adzic', team: 'Sassuolo', role: 'C' },
  { name: 'Akinsanmiro', team: 'Monza', role: 'C' },
  { name: 'Alajbegovic', team: 'Juventus', role: 'C' },
  { name: 'Almqvist', team: 'Parma', role: 'C' },
  { name: 'Amondarain', team: 'Bologna', role: 'C' },
  { name: 'Amorim', team: 'Genoa', role: 'C' },
  { name: 'Anjorin', team: 'Torino', role: 'C' },
  { name: 'Atta', team: 'Fiorentina', role: 'C' },
  { name: 'Bakola', team: 'Sassuolo', role: 'C' },
  { name: 'Baldanzi', team: 'Genoa', role: 'C' },
  { name: 'Barella', team: 'Inter', role: 'C' },
  { name: 'Basic', team: 'Venezia', role: 'C' },
  { name: 'Baturina', team: 'Como', role: 'C' },
  { name: 'Belahyane', team: 'Lazio', role: 'C' },
  { name: 'Berisha M.', team: 'Lecce', role: 'C' },
  { name: 'Bernabè', team: 'Parma', role: 'C' },
  { name: 'Bernardeschi', team: 'Bologna', role: 'C' },
  { name: 'Boloca', team: 'Sassuolo', role: 'C' },
  { name: 'Brescianini', team: 'Fiorentina', role: 'C' },
  { name: 'Busio', team: 'Venezia', role: 'C' },
  { name: 'Cacciamani', team: 'Torino', role: 'C' },
  { name: 'Calhanoglu', team: 'Inter', role: 'C' },
  { name: 'Calò', team: 'Frosinone', role: 'C' },
  { name: 'Camara A.', team: 'Udinese', role: 'C' },
  { name: 'Cambiaghi', team: 'Bologna', role: 'C' },
  { name: 'Cancellieri', team: 'Lazio', role: 'C' },
  { name: 'Caqueret', team: 'Como', role: 'C' },
  { name: 'Casadei', team: 'Torino', role: 'C' },
  { name: 'Cataldi', team: 'Lazio', role: 'C' },
  { name: 'Chakvetadze', team: 'Udinese', role: 'C' },
  { name: 'Chukwueze', team: 'Milan', role: 'C' },
  { name: 'Cichella', team: 'Frosinone', role: 'C' },
  { name: 'Cissé A.', team: 'Milan', role: 'C' },
  { name: 'Ciurria', team: 'Monza', role: 'C' },
  { name: 'Colombo L.', team: 'Monza', role: 'C' },
  { name: 'Colpani', team: 'Monza', role: 'C' },
  { name: 'Conceicao', team: 'Juventus', role: 'C' },
  { name: 'Coulibaly L.', team: 'Lecce', role: 'C' },
  { name: 'Cremaschi', team: 'Parma', role: 'C' },
  { name: 'Cristante', team: 'Roma', role: 'C' },
  { name: 'Da Cunha', team: 'Como', role: 'C' },
  { name: 'Dagasso', team: 'Venezia', role: 'C' },
  { name: 'De Bruyne', team: 'Napoli', role: 'C' },
  { name: 'De Roon', team: 'Atalanta', role: 'C' },
  { name: 'Deiola', team: 'Cagliari', role: 'C' },
  { name: 'Dele-Bashiru', team: 'Lazio', role: 'C' },
  { name: 'Diallo O.', team: 'Parma', role: 'C' },
  { name: 'Diouf', team: 'Inter', role: 'C' },
  { name: 'Dominguez B.', team: 'Sassuolo', role: 'C' },
  { name: 'Douglas Luiz', team: 'Juventus', role: 'C' },
  { name: 'Duncan', team: 'Venezia', role: 'C' },
  { name: 'Ederson D.S.', team: 'Atalanta', role: 'C' },
  { name: 'Ekkelenkamp', team: 'Udinese', role: 'C' },
  { name: 'El Aynaoui', team: 'Roma', role: 'C' },
  { name: 'El Azzouzi A.', team: 'Frosinone', role: 'C' },
  { name: 'El Azzouzi O.', team: 'Bologna', role: 'C' },
  { name: 'Ellertsson', team: 'Genoa', role: 'C' },
  { name: 'Fabbian', team: 'Fiorentina', role: 'C' },
  { name: 'Fadera', team: 'Como', role: 'C' },
  { name: 'Fagioli', team: 'Fiorentina', role: 'C' },
  { name: 'Fazzini', team: 'Cagliari', role: 'C' },
  { name: 'Felici', team: 'Cagliari', role: 'C' },
  { name: 'Ferguson', team: 'Bologna', role: 'C' },
  { name: 'Fini', team: 'Frosinone', role: 'C' },
  { name: 'Fitz-Jim', team: 'Torino', role: 'C' },
  { name: 'Fofana Sa.', team: 'Lecce', role: 'C' },
  { name: 'Fofana Y.', team: 'Milan', role: 'C' },
  { name: 'Folorunsho', team: 'Napoli', role: 'C' },
  { name: 'Forson O.', team: 'Monza', role: 'C' },
  { name: 'Frattesi', team: 'Lazio', role: 'C' },
  { name: 'Frendrup', team: 'Genoa', role: 'C' },
  { name: 'Gaetano', team: 'Atalanta', role: 'C' },
  { name: 'Gandelman', team: 'Lecce', role: 'C' },
  { name: 'Gelli F.', team: 'Frosinone', role: 'C' },
  { name: 'Gilmour', team: 'Napoli', role: 'C' },
  { name: 'Gineitis', team: 'Torino', role: 'C' },
  { name: 'Gorter', team: 'Lecce', role: 'C' },
  { name: 'Grillitsch', team: 'Frosinone', role: 'C' },
  { name: 'Gudmundsson A.', team: 'Fiorentina', role: 'C' },
  { name: 'Hasa', team: 'Frosinone', role: 'C' },
  { name: 'Helgason', team: 'Venezia', role: 'C' },
  { name: 'Iannoni', team: 'Sassuolo', role: 'C' },
  { name: 'Ilic', team: 'Torino', role: 'C' },
  { name: 'Ilkhan', team: 'Torino', role: 'C' },
  { name: 'Isaksen', team: 'Lazio', role: 'C' },
  { name: 'Jashari', team: 'Milan', role: 'C' },
  { name: 'Kaba', team: 'Lecce', role: 'C' },
  { name: 'Karlstrom', team: 'Udinese', role: 'C' },
  { name: 'Keita M.', team: 'Parma', role: 'C' },
  { name: 'Kone B.', team: 'Frosinone', role: 'C' },
  { name: 'Konè I.', team: 'Sassuolo', role: 'C' },
  { name: 'Konè M.', team: 'Roma', role: 'C' },
  { name: 'Koopmeiners', team: 'Juventus', role: 'C' },
  { name: 'Koutsoupias', team: 'Frosinone', role: 'C' },
  { name: 'Lahdo', team: 'Como', role: 'C' },
  { name: 'Liberali', team: 'Como', role: 'C' },
  { name: 'Lipani', team: 'Sassuolo', role: 'C' },
  { name: 'Liteta', team: 'Cagliari', role: 'C' },
  { name: 'Lobotka', team: 'Napoli', role: 'C' },
  { name: 'Locatelli', team: 'Juventus', role: 'C' },
  { name: 'Loftus-Cheek', team: 'Milan', role: 'C' },
  { name: 'Luis Henrique', team: 'Inter', role: 'C' },
  { name: 'Maleh', team: 'Lecce', role: 'C' },
  { name: 'Mandragora', team: 'Fiorentina', role: 'C' },
  { name: 'Masini', team: 'Frosinone', role: 'C' },
  { name: 'Mastantuono', team: 'Fiorentina', role: 'C' },
  { name: 'Matic', team: 'Sassuolo', role: 'C' },
  { name: 'Mckennie', team: 'Juventus', role: 'C' },
  { name: 'Mctominay', team: 'Napoli', role: 'C' },
  { name: 'Meichtry', team: 'Genoa', role: 'C' },
  { name: 'Messias', team: 'Genoa', role: 'C' },
  { name: 'Milla', team: 'Como', role: 'C' },
  { name: 'Miller L.', team: 'Udinese', role: 'C' },
  { name: 'Miretti', team: 'Juventus', role: 'C' },
  { name: 'Mkhitaryan', team: 'Inter', role: 'C' },
  { name: 'Modric', team: 'Milan', role: 'C' },
  { name: 'Moro N.', team: 'Bologna', role: 'C' },
  { name: 'Musah', team: 'Milan', role: 'C' },
  { name: 'Ndour', team: 'Fiorentina', role: 'C' },
  { name: 'Ngom', team: 'Lecce', role: 'C' },
  { name: 'Nicolussi Caviglia', team: 'Parma', role: 'C' },
  { name: 'Njie', team: 'Torino', role: 'C' },
  { name: 'Odgaard', team: 'Bologna', role: 'C' },
  { name: 'Ordonez C.', team: 'Parma', role: 'C' },
  { name: 'Oristanio', team: 'Torino', role: 'C' },
  { name: 'Orsolini', team: 'Bologna', role: 'C' },
  { name: 'Oulai', team: 'Fiorentina', role: 'C' },
  { name: 'Pasalic', team: 'Atalanta', role: 'C' },
  { name: 'Paz N.', team: 'Como', role: 'C' },
  { name: 'Pellegrini Lo.', team: 'Roma', role: 'C' },
  { name: 'Perez K.', team: 'Venezia', role: 'C' },
  { name: 'Perrone', team: 'Como', role: 'C' },
  { name: 'Pessina', team: 'Monza', role: 'C' },
  { name: 'Pierotti', team: 'Lecce', role: 'C' },
  { name: 'Piotrowski', team: 'Udinese', role: 'C' },
  { name: 'Pisilli', team: 'Roma', role: 'C' },
  { name: 'Pobega', team: 'Bologna', role: 'C' },
  { name: 'Politano', team: 'Napoli', role: 'C' },
  { name: 'Prati', team: 'Cagliari', role: 'C' },
  { name: 'Przyborek', team: 'Lazio', role: 'C' },
  { name: 'Pulisic', team: 'Milan', role: 'C' },
  { name: 'Rabiot', team: 'Milan', role: 'C' },
  { name: 'Ricci S.', team: 'Milan', role: 'C' },
  { name: 'Rodriguez Je.', team: 'Como', role: 'C' },
  { name: 'Romano', team: 'Cagliari', role: 'C' },
  { name: 'Rovella', team: 'Lazio', role: 'C' },
  { name: 'Rowe', team: 'Bologna', role: 'C' },
  { name: 'Saelemaekers', team: 'Milan', role: 'C' },
  { name: 'Samardzic', team: 'Atalanta', role: 'C' },
  { name: 'Schmid', team: 'Frosinone', role: 'C' },
  { name: 'Sohm', team: 'Venezia', role: 'C' },
  { name: 'Sorensen O.', team: 'Parma', role: 'C' },
  { name: 'Sow', team: 'Genoa', role: 'C' },
  { name: 'Stankovic A.', team: 'Inter', role: 'C' },
  { name: 'Sucic P.', team: 'Inter', role: 'C' },
  { name: 'Sulemana I.', team: 'Atalanta', role: 'C' },
  { name: 'Taylor K.', team: 'Lazio', role: 'C' },
  { name: 'Thorstvedt', team: 'Sassuolo', role: 'C' },
  { name: 'Thuram K.', team: 'Juventus', role: 'C' },
  { name: 'Traore Hj.', team: 'Genoa', role: 'C' },
  { name: 'Unai Gomez', team: 'Udinese', role: 'C' },
  { name: 'Venturino', team: 'Genoa', role: 'C' },
  { name: 'Vergara', team: 'Napoli', role: 'C' },
  { name: 'Vlasic', team: 'Torino', role: 'C' },
  { name: 'Volpato', team: 'Sassuolo', role: 'C' },
  { name: 'Winks', team: 'Cagliari', role: 'C' },
  { name: 'Zaccagni', team: 'Lazio', role: 'C' },
  { name: 'Zalewski', team: 'Atalanta', role: 'C' },
  { name: 'Zambo Anguissa', team: 'Napoli', role: 'C' },
  { name: 'Zaniolo', team: 'Udinese', role: 'C' },
  { name: 'Zarraga', team: 'Udinese', role: 'C' },
  { name: 'Zerbin', team: 'Frosinone', role: 'C' },
  { name: 'Zhegrova', team: 'Juventus', role: 'C' },
  { name: 'Zielinski', team: 'Inter', role: 'C' },

  // --- ATTACCANTI (89) ---
  { name: 'Adams A.', team: 'Venezia', role: 'A' },
  { name: 'Adams C.', team: 'Torino', role: 'A' },
  { name: 'Adorante', team: 'Venezia', role: 'A' },
  { name: 'Albarracin', team: 'Cagliari', role: 'A' },
  { name: 'Azon', team: 'Como', role: 'A' },
  { name: 'Bayo V.', team: 'Udinese', role: 'A' },
  { name: 'Berardi', team: 'Sassuolo', role: 'A' },
  { name: 'Boga', team: 'Juventus', role: 'A' },
  { name: 'Bonny', team: 'Inter', role: 'A' },
  { name: 'Borrelli', team: 'Cagliari', role: 'A' },
  { name: 'Bowie', team: 'Sassuolo', role: 'A' },
  { name: 'Buksa', team: 'Udinese', role: 'A' },
  { name: 'Camarda', team: 'Milan', role: 'A' },
  { name: 'Castro S.', team: 'Roma', role: 'A' },
  { name: 'Colombo', team: 'Genoa', role: 'A' },
  { name: 'Cutrone', team: 'Monza', role: 'A' },
  { name: 'David', team: 'Juventus', role: 'A' },
  { name: 'Davis K.', team: 'Udinese', role: 'A' },
  { name: 'De Ketelaere', team: 'Atalanta', role: 'A' },
  { name: 'Dia', team: 'Lazio', role: 'A' },
  { name: 'Diao', team: 'Como', role: 'A' },
  { name: 'Douvikas', team: 'Como', role: 'A' },
  { name: 'Dovbyk', team: 'Bologna', role: 'A' },
  { name: 'Dybala', team: 'Roma', role: 'A' },
  { name: 'Ekhator', team: 'Juventus', role: 'A' },
  { name: 'Elphege', team: 'Parma', role: 'A' },
  { name: 'Esposito F.P.', team: 'Inter', role: 'A' },
  { name: 'Esposito Se.', team: 'Cagliari', role: 'A' },
  { name: 'Frigan', team: 'Parma', role: 'A' },
  { name: 'Geubbels', team: 'Lecce', role: 'A' },
  { name: 'Ghedjemis', team: 'Frosinone', role: 'A' },
  { name: 'Gimenez', team: 'Milan', role: 'A' },
  { name: 'Giovane', team: 'Napoli', role: 'A' },
  { name: 'Gueye', team: 'Udinese', role: 'A' },
  { name: 'Havel', team: 'Genoa', role: 'A' },
  { name: 'Hojlund', team: 'Napoli', role: 'A' },
  { name: 'Kean', team: 'Fiorentina', role: 'A' },
  { name: 'Kevin Carlos', team: 'Cagliari', role: 'A' },
  { name: 'Kolo Muani', team: 'Juventus', role: 'A' },
  { name: 'Krstovic', team: 'Atalanta', role: 'A' },
  { name: 'Kuhn', team: 'Como', role: 'A' },
  { name: 'Kulenovic', team: 'Torino', role: 'A' },
  { name: 'Kvernadze', team: 'Frosinone', role: 'A' },
  { name: 'Lang', team: 'Napoli', role: 'A' },
  { name: 'Lauberbach', team: 'Venezia', role: 'A' },
  { name: 'Lauriente', team: 'Sassuolo', role: 'A' },
  { name: 'Leao', team: 'Milan', role: 'A' },
  { name: 'Lisman', team: 'Venezia', role: 'A' },
  { name: 'Lontani', team: 'Parma', role: 'A' },
  { name: 'Lucca', team: 'Napoli', role: 'A' },
  { name: 'Maldini', team: 'Cagliari', role: 'A' },
  { name: 'Malen', team: 'Roma', role: 'A' },
  { name: 'Martinez L.', team: 'Inter', role: 'A' },
  { name: 'Mendy P.', team: 'Cagliari', role: 'A' },
  { name: 'Milik', team: 'Juventus', role: 'A' },
  { name: 'Morata', team: 'Como', role: 'A' },
  { name: 'Moro L.', team: 'Sassuolo', role: 'A' },
  { name: 'Mota', team: 'Monza', role: 'A' },
  { name: 'Mutandwa', team: 'Cagliari', role: 'A' },
  { name: 'N\'Dri', team: 'Lecce', role: 'A' },
  { name: 'Neres', team: 'Napoli', role: 'A' },
  { name: 'Nkunku', team: 'Milan', role: 'A' },
  { name: 'Noslin', team: 'Lazio', role: 'A' },
  { name: 'Pellegrino M.', team: 'Fiorentina', role: 'A' },
  { name: 'Petagna', team: 'Monza', role: 'A' },
  { name: 'Piccoli', team: 'Bologna', role: 'A' },
  { name: 'Pinamonti', team: 'Sassuolo', role: 'A' },
  { name: 'Raimondo', team: 'Frosinone', role: 'A' },
  { name: 'Ramos G.', team: 'Milan', role: 'A' },
  { name: 'Raspadori', team: 'Atalanta', role: 'A' },
  { name: 'Ratkov', team: 'Lazio', role: 'A' },
  { name: 'Robinson J.', team: 'Monza', role: 'A' },
  { name: 'Romero D.', team: 'Parma', role: 'A' },
  { name: 'Rrahmani Al.', team: 'Venezia', role: 'A' },
  { name: 'Santos A.', team: 'Napoli', role: 'A' },
  { name: 'Scamacca', team: 'Atalanta', role: 'A' },
  { name: 'Simeone', team: 'Torino', role: 'A' },
  { name: 'Soulè', team: 'Roma', role: 'A' },
  { name: 'Stulic', team: 'Lecce', role: 'A' },
  { name: 'Sulemana K.', team: 'Atalanta', role: 'A' },
  { name: 'Thuram', team: 'Inter', role: 'A' },
  { name: 'Tourè E.', team: 'Parma', role: 'A' },
  { name: 'Trepy', team: 'Cagliari', role: 'A' },
  { name: 'Varela G.', team: 'Monza', role: 'A' },
  { name: 'Vaz', team: 'Roma', role: 'A' },
  { name: 'Vitinha O.', team: 'Genoa', role: 'A' },
  { name: 'Yeboah J.', team: 'Venezia', role: 'A' },
  { name: 'Yildiz', team: 'Juventus', role: 'A' },
  { name: 'Zapata D.', team: 'Torino', role: 'A' }
];
